config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'users#index'
  resources :users
  resources :categories do
    collection do
      get 'api_product_no'
    end
    resources :products
  end

  resources :charges

end

app/models/category.rb
class Category < ActiveRecord::Base

  validates :name, presence: true

  has_many :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true

  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user! , only: [:api_product_no]

  def api_product_no
    @flag='false'
    if params[:appId]
      @category=Category.find(params[:appId]) rescue nil
      if params[:appSecrete]
        if @category.app_secrete==params[:appSecrete]
          @products=@category.products
          @flag='true'
        else
          @message="Wrong appSecrete!"
        end
      else
        @message="appSecrete required!"
      end
    else
      @message="appId required!"
    end
  end

  def index
   @categories=Category.all
  end

  def new
    @category=Category.new
  end

  def show
    @category=Category.find(params[:id])
  end

  def create
    @category=Category.new(params_category)
    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category=Category.find(params[:id])
  end

  def update
    @category=Category.find(params[:id])
    if @category.update(params_category)
      flash[:notice] = "Category was successfully updated."
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category=Category.find(params[:id])
    if @category.destroy
      flash[:alert] = "Category was successfully deleted."
      redirect_to categories_path
    end
  end

  protected

  def params_category
    params.require(:category).permit(:name)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # raise params.inspect
    # Amount in cents
    @amount = 10000

    customer = Stripe::Customer.create(
        :email => 'example@stripe.com',
        :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @category=Category.find(params[:category_id])
    @product=@category.products.new
  end

  def create
    @category=Category.find(params[:category_id])
    @product=@category.products.build(params_product)
    if @product.save
      flash[:notice] = "Product was successfully created."
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def edit
    @category=Category.find(params[:category_id])
    @product=Product.find(params[:id])
  end

  def update
    @category=Category.find(params[:category_id])
    @product=Product.find(params[:id])
    if @product.update(params_product)
      flash[:notice] = "Product was successfully updated."
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category=Category.find(params[:category_id])
    @product=Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Product was successfully deleted."
      redirect_to category_path(@category)
    end
  end

  protected

  def params_product
    params.require(:product).permit(:name, :price, :details)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  #
  # def new
  #   flash[:notice] = 'Registrations are not open yet, but please check back soon'
  #   redirect_to new_user_session_path
  # end
  #
  # def create
  #   flash[:notice] = 'Registrations are not open yet, but please check back soon'
  #   redirect_to new_user_session_path
  # end

  def sign_out
    super
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
     # raise DateTime.now.new_offset(0).inspect
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@category.errors.count, "error") %> prohibited
            this category from being saved:
          </h2>
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name, :placeholder=>'Category Name' %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/categories/edit.html.erb
<h4>Category edit form </h4>
<%= render 'form' %>

app/views/categories/index.html.erb
<% if @categories.any? %>
    <% @categories.each do |category| %>
        <div>
          <%= link_to category.name , category_path(category) %>
          <%= link_to 'Edit' , edit_category_path(category) %>
          <%= link_to 'Delete' , category_path(category) ,method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>
    <% end %>
<% end %>

<br>
<br>
<br>
<%= link_to 'Add New Category', new_category_path %>

app/views/categories/new.html.erb
<h4>Category form </h4>
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container_div">
<h2><%= @category.name %></h2>
<% if @category.products.any?  %>
    <% @category.products.each do |product| %>
          <%= form_tag charges_path do %>
              <article>
                <label class="amount">
                  <span>Price: $<%= product.price %></span>
                </label>
              </article>

              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="A month's subscription"
                      data-amount="<%= (product.price)*100 %>"
                      data-locale="auto"></script>
          <% end %>
        <div style="margin: 5px; padding: 5px; border: 1px solid #dadada">
         Name: <%= product.name %><br>
         Price: $<span style="color: red" class="price_amount"><%= product.price %></span><br>
         Details:  <%= product.details %><br>
          <button class="customButton">Purchase</button>
          <%= link_to 'Edit' , edit_category_product_path(@category, product) %>
          <%= link_to 'Delete' , category_product_path(@category, product) ,method: :delete, data: { confirm: 'Are you sure?' }%>
          <%= social_share_button_tag(product.name, :url => 'www.get-togather.com') %>
        </div>


    <% end %>
<% end %>
<br>
<%= link_to 'Add new product', new_category_product_path(@category) %><br>
<%= link_to 'All Categories', categories_path %>
</div>

<div id="editor"></div>
<button id="create_pdf">generate PDF</button>
<button id="btnPrint">print this</button>
<script type="text/javascript" src="//cdn.rawgit.com/niklasvh/html2canvas/0.5.0-alpha2/dist/html2canvas.min.js"></script>
<script src="//mrrio.github.io/jsPDF/dist/jspdf.debug.js"></script>

<script type="text/javascript">

    $(document).ready(function(){
           // for print start
        $("#btnPrint").click(function () {
            var contents = $(".container_div").html();
            var frame1 = $('<iframe />');
            frame1[0].name = "frame1";
            frame1.css({ "position": "absolute", "top": "-1000000px" });
            $("body").append(frame1);
            var frameDoc = frame1[0].contentWindow ? frame1[0].contentWindow : frame1[0].contentDocument.document ? frame1[0].contentDocument.document : frame1[0].contentDocument;
            frameDoc.document.open();
            //Create a new HTML document.
            frameDoc.document.write('<html><head><title>Convergent</title>');
            frameDoc.document.write('<style type="text/css" >.price_amount{color: red;} </style></head><body>');
            //Append the external CSS file.
            frameDoc.document.write('<link href="style.css" rel="stylesheet" type="text/css" />');
            //Append the DIV contents.
            frameDoc.document.write(contents);
            frameDoc.document.write('</body></html>');
            frameDoc.document.close();
            setTimeout(function () {
                window.frames["frame1"].focus();
                window.frames["frame1"].print();
                frame1.remove();
            }, 500);
        });
        // for print end


//        var doc = new jsPDF();
//        var specialElementHandlers = {
//            '#editor': function (element, renderer) {
//                return true;
//            }
//        };
//
//        $('#cmd').click(function () {
//            doc.fromHTML($('.container_div').html(), 15, 15, {
//                'width': 170,
//                'elementHandlers': specialElementHandlers
//            });
//            doc.save('sample-file.pdf');
//        });
        (function(){
            var
                    form = $('.container_div'),
                    cache_width = form.width(),
                    a4  =[ 595.28,  841.89];  // for a4 size paper width and height

            $('#create_pdf').on('click',function(){
                $('body').scrollTop(0);
                createPDF();
            });
//create pdf
            function createPDF(){
                getCanvas().then(function(canvas){
                    var
                            img = canvas.toDataURL("image/png"),
                            doc = new jsPDF({
                                unit:'px',
                                format:'a4'
                            });
//                    img.print()
                    doc.addImage(img, 'JPEG', 20, 20);
                    doc.save('techumber-html-to-pdf.pdf');
                    form.width(cache_width);
                });
            }

// create canvas object
            function getCanvas(){
                form.width((a4[0]*1.33333) -80).css('max-width','none');
                return html2canvas(form,{
                    imageTimeout:2000,
                    removeContainer:true
                });
            }

        }());
    })

</script>

<!--<script src="https://checkout.stripe.com/checkout.js"></script>-->

<script>
//    var handler = StripeCheckout.configure({
//        key: 'pk_test_6pRNASCoBOKtIshFeQd4XMUh',
//        image: '/img/documentation/checkout/marketplace.png',
//        locale: 'auto',
//        token: function(token) {
//            // Use the token to create the charge with a server-side script.
//            // You can access the token ID with `token.id`
//        }
//    });
//
//    $('.customButton').on('click', function(e) {
//        // Open Checkout with further options
//        var price=parseInt($(this).parent().find('.price_amount').text(),10)
//        handler.open({
//            name: 'Stripe.com',
//            description: '2 widgets',
//            amount: price*100
//        });
//        e.preventDefault();
//    });
//
//    // Close Checkout on page navigation
//    $(window).on('popstate', function() {
//        handler.close();
//    });
</script>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$<%= @amount/100 %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <article>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="500"
            data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleD1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>
<% if flash[:notice] %>
<p>
  <%= flash[:notice] %>
</p>
<% end %>
<% if flash[:alert] %>
    <p>
      <%= flash[:alert] %>
    </p>
<% end %>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for [@category, @product] do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@product.errors.count, "error") %> prohibited
            this product from being saved:
          </h2>
          <ul>
            <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name, :placeholder=>'Product Name' %>
    </p>
    <p>
      <%= f.label :price %>
      <%= f.text_field :price, :placeholder=>'Product Price' %>
    </p>
    <p>
      <%= f.label :details %>
      <%= f.text_area :details, :placeholder=>'Product Details' %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product form</h2>
<%= render 'form' %>

app/views/products/new.html.erb
<h2>New Product Add</h2>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Index</h1>
<%= link_to 'Categories', categories_path %>